# CONFIGURATIONS
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    frontend: ${URL_FRONTEND}
  profiles:
    active: ${PROFILE:DEV}
  flyway:
    locations: classpath:db/migration, classpath:db/testdata
    baselineOnMigrate: true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
    hibernate:
      ddl-auto: none

google:
  clientId: 1008609354061-hq00k0otaiooh4evgquedqkntrhputai.apps.googleusercontent.com
  baseUrl: https://www.googleapis.com/oauth2/v1/userinfo?access_token=