INSERT INTO skills (name, description, label_id)
VALUES
    -- FRONTEND
    ('HTMLCSS', 'Lorem ipsum dolor', 1),
    ('JavaScript', 'Lorem ipsum dolor', 1),
    ('ReactJS', 'Lorem ipsum dolor', 1),
    ('Angular', 'Lorem ipsum dolor', 1),
    ('Vue.js', 'Lorem ipsum dolor', 1),
    ('Bootstrap Material Tailwind', 'Lorem ipsum dolor', 1),
    ('Responsive Design', 'Lorem ipsum dolor', 1),
    ('Unit test (e.g. Jasmine, Jest, JUnit, TestNG)', 'Lorem ipsum dolor', 1),
    ('Blazor', 'Lorem ipsum dolor', 1),
    -- BACKEND
    ('Java', 'Lorem ipsum dolor', 2),
    ('NodeJS', 'Lorem ipsum dolor', 2),
    ('Go', 'Lorem ipsum dolor', 2),
    ('.NET', 'Lorem ipsum dolor', 2),
    ('Python', 'Lorem ipsum dolor', 2),
    ('EIP Message Brokers Streams', 'Lorem ipsum dolor', 2),
    ('REST APIs gRPC Hypermedia protocols', 'Lorem ipsum dolor', 2),
    ('Web Sockets', 'Lorem ipsum dolor', 2),
    ('Typescript', 'Lorem ipsum dolor', 2),
    -- MOBILE
    ('iOS Development', 'Lorem ipsum dolor', 3),
    ('Android Development', 'Lorem ipsum dolor', 3),
    ('React Native', 'Lorem ipsum dolor', 3),
    ('Flutter', 'Lorem ipsum dolor', 3),
    ('Xamarin', 'Lorem ipsum dolor', 3),
    ('Hybrid', 'Lorem ipsum dolor', 3),
    --DATA MANAGEMENT
    ('RDB Database frontend-dev', 'Lorem ipsum dolor', 4),
    ('RDB Database Modeling', 'Lorem ipsum dolor', 4),
    ('RDB Query Building', 'Lorem ipsum dolor', 4),
    ('NoSQL', 'Lorem ipsum dolor', 4),
    ('Elastic Search', 'Lorem ipsum dolor', 4),
    ('Amazon RDS', 'Lorem ipsum dolor', 4),
    ('Google Datastore', 'Lorem ipsum dolor', 4),
    ('Firebase', 'Lorem ipsum dolor', 4),
    ('Amazon Athena', 'Lorem ipsum dolor', 4),
    ('AWS Glue', 'Lorem ipsum dolor', 4),
    --INFRA DEVOPS
    ('Linux', 'Lorem ipsum dolor', 5),
    ('WebServer (e.g. Nginx, Apache)', 'Lorem ipsum dolor', 5),
    ('Containers (e.g. Docker, Podman)', 'Lorem ipsum dolor', 5),
    ('Containers Orchestration (e.g. Docker Swarm, K8s)', 'Lorem ipsum dolor', 5),
    ('CICD (e.g. Jenkins, Bamboo, GH Actions)', 'Lorem ipsum dolor', 5),
    ('Deployment Orchestration (e.g. Chef, Puppet)', 'Lorem ipsum dolor', 5),
    ('Production Support & Maintenance (Monitoring, Troubleshooting & HA)', 'Lorem ipsum dolor', 5),
    ('Network Tools (load balancers, reverse proxy, etc)', 'Lorem ipsum dolor', 5),
    ('Infrastructure as Code (e.g. Terraform, CloudFormation)', 'Lorem ipsum dolor', 5),
    -- AREA SKILL
    ('Project Management', 'Lorem ipsum dolor', 6),
    ('Troubleshooting', 'Lorem ipsum dolor', 6),
    ('Negotiation Estimation', 'Lorem ipsum dolor', 6),
    ('Best Practices Design Patterns', 'Lorem ipsum dolor', 6),
    ('Functional Programming', 'Lorem ipsum dolor', 6),
    ('Microservices Architecture', 'Lorem ipsum dolor', 6),
    ('Security (TLS, SSL, Oauth2, JWT, AD, etc)', 'Lorem ipsum dolor', 6),
    ('Non-functional requirements (e.g. HA, performance, maintainability)', 'Lorem ipsum dolor', 6),
    ('Performance testing tools (e.g. Gatling, JMeter)', 'Lorem ipsum dolor', 6),
    -- CLOUD AI
    ('GCP (Google Platform)', 'Lorem ipsum dolor', 7),
    ('AWS (Amazon Web Services)', 'Lorem ipsum dolor', 7),
    ('Machine Learning (e.g. NumPy, AutoML)', 'Lorem ipsum dolor', 7),
    ('Deep Learning (e.g. PyTorch, TensorFlow)', 'Lorem ipsum dolor', 7),
    ('NLU: RASA', 'Lorem ipsum dolor', 7),
    ('NLU: DialogFlow', 'Lorem ipsum dolor', 7),
    ('NLU: others (e.g. Watson, Lex)', 'Lorem ipsum dolor', 7),
    ('Multi- (e.g Foundry)', 'Lorem ipsum dolor', 7),
    ('GCP BigQuery', 'Lorem ipsum dolor', 7),
    ('Cognitive Services (e.g Watson, Azure, Vision)', 'Lorem ipsum dolor', 7),
    -- METHODOLOGIES
    ('Agile Methodologies', 'Lorem ipsum dolor', 8),
    ('SAFe', 'Lorem ipsum dolor', 8),
    ('Waterfall', 'Lorem ipsum dolor', 8),
    ('BDD TDD (Behavior Test)', 'Lorem ipsum dolor', 8),
    ('DDD (Domain Driven Design)', 'Lorem ipsum dolor', 8),
    ('Clean Architecture', 'Lorem ipsum dolor', 8),
    -- SCRUM
    ('Scrum Master', 'Lorem ipsum dolor', 9),
    ('Product Owner', 'Lorem ipsum dolor', 9);